### ISSUE TITLE
error when trying to run npm run start

### ISSUE THREAD

**Issue by amouratoglou** [DhiWise/dhiwise-nodejs#22]
### Current Behavior:
When I try to run the project
`npm i && npm run start`

```
Error:
found 18 vulnerabilities (12 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> nodejs-code-generator@0.0.0 start /Users/agustin/Dev/dhiwise-nodejs
> lerna run start

lerna notice cli v4.0.0
lerna info Executing command in 2 packages: "npm run start"
lerna ERR! npm run start exited 1 in '@nodejs-code-generator/server'
lerna ERR! npm run start stdout:

> @nodejs-code-generator/server@1.1.0 start /Users/agustin/Dev/dhiwise-nodejs/packages/server
> node --inspect=0.0.0.0 app.js

lerna ERR! npm run start stderr:
Debugger listening on ws://0.0.0.0:9229/f8808c4b-4b93-41e3-bc08-4a54878e4c48
For help, see: https://nodejs.org/en/docs/inspector
/Users/agustin/Dev/dhiwise-nodejs/packages/server/models/Repo/index.js:19
    if (result?.error) {
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/agustin/Dev/dhiwise-nodejs/packages/server/repo/project.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/agustin/Dev/dhiwise-nodejs/packages/server/controllers/web/project/index.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodejs-code-generator/server@1.1.0 start: `node --inspect=0.0.0.0 app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodejs-code-generator/server@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agustin/.npm/_logs/2022-01-27T02_19_52_924Z-debug.log
lerna ERR! npm run start exited 1 in '@nodejs-code-generator/server'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-code-generator@0.0.0 start: `lerna run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-code-generator@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agustin/.npm/_logs/2022-01-27T02_19_52_967Z-debug.log
```

### Environment:
macos m1
node 12.22.7

**Comment by saloni137** [comment]
Hello @amouratoglou Please update your node version to 14 or higher. Thank you.
