### ISSUE TITLE
[BUG] Unable to resolve dependency

### ISSUE THREAD

**Issue by RashiqAzhan** [DhiWise/dhiwise-nodejs#26]
### Current Behavior:
`npm i` or `yarn` cannot resolve the dependency.

### Expected Behavior:
Git cloned project should resolve all dependencies.

### Steps To Reproduce:
Follow steps outlined [here](https://github.com/DhiWise/dhiwise-nodejs#get-started) in the docs.

### Anything else:
Terminal Output of error.
```js
lerna ERR! npm install exited 1 in 'nodejs-code-generator'
lerna ERR! npm install stderr:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nodejs-code-generator@0.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-dropdown-tree-select@0.0.0-semantic-release
npm ERR! node_modules/react-dropdown-tree-select
npm ERR!   react-dropdown-tree-select@"git+https://github.com/DhiWise/react-dropdown-tree-select" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See .../.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2022-03-02T17_22_25_113Z-debug-0.log
lerna ERR! npm install exited 1 in 'nodejs-code-generator'
npm ERR! code 1
npm ERR! path .../Downloads/Code/hoa_web_app/dhiwise-nodejs
npm ERR! command failed
npm ERR! command sh -c lerna clean -y && lerna bootstrap --hoist
```

**Comment by Tzvetelin88** [comment]
The same here

**Comment by saloni137** [comment]
Hi, @RashiqAzhan I am not able to re-generate the issue. please provide your Environment(os,nodejs and npm versions).

**Comment by 0x41mmarVM** [comment]
Same here. Node v16.13.1 running on Windows, but I suspect Windows isn't the issue, just the Node version.

**Comment by saloni137** [comment]
> Same here. Node v16.13.1 running on Windows, but I suspect Windows isn't the issue, just the Node version.

@0x41mmarVM It supports node version > 14. can you please provide an error log?

**Comment by 0x41mmarVM** [comment]
@saloni137 terminal output is the same as @RashiqAzhan provided:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nodejs-code-generator@0.0.0
npm ERR! Found: lerna@4.0.0
npm ERR! node_modules/lerna
npm ERR!   dev lerna@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer lerna@"^3.0.0" from cz-lerna-changelog@2.0.3
npm ERR! node_modules/cz-lerna-changelog
npm ERR!   dev cz-lerna-changelog@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\[redacted]\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[redacted]\AppData\Local\npm-cache\_logs\2022-03-27T19_01_48_798Z-debug.log
```

Node version 16.13.1, tested with both NPM version 8.1.4 and 8.5.5

Verbose log:
```
0 verbose cli [
0 verbose cli   'C:\\node\\node.exe',
0 verbose cli   'C:\\Users\\[redacted]\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'i'
0 verbose cli ]
1 info using npm@8.1.4
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\Projects\DMS\d\dhiwise-nodejs\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\[redacted]\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\[redacted]\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 0ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 6ms
26 timing npm:load Completed in 25ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 24ms
30 timing idealTree:userRequests Completed in 0ms
31 silly idealTree buildDeps
32 silly fetch manifest lerna@^4.0.0
33 http fetch GET 200 https://registry.npmjs.org/lerna 3089ms (cache revalidated)
34 silly fetch manifest commitizen@^4.2.4
35 http fetch GET 200 https://registry.npmjs.org/commitizen 3622ms (cache revalidated)
36 silly fetch manifest conventional-github-releaser@^3.1.2
37 http fetch GET 200 https://registry.npmjs.org/conventional-github-releaser 1118ms (cache revalidated)
38 silly fetch manifest cz-lerna-changelog@^2.0.3
39 http fetch GET 200 https://registry.npmjs.org/cz-lerna-changelog 782ms (cache revalidated)
40 silly fetch manifest lerna@^3.0.0
41 timing idealTree Completed in 8681ms
42 timing command:i Completed in 8698ms
43 verbose stack Error: unable to resolve dependency tree
43 verbose stack     at Arborist.[failPeerConflict] (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1356:25)
43 verbose stack     at Arborist.[loadPeerSet] (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1322:34)
43 verbose stack     at async Arborist.[buildDepStep] (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:930:11)
43 verbose stack     at async Arborist.buildIdealTree (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:216:7)
43 verbose stack     at async Promise.all (index 1)
43 verbose stack     at async Arborist.reify (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:149:5)
43 verbose stack     at async Install.exec (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:157:5)
43 verbose stack     at async module.exports (C:\Users\[redacted]\AppData\Roaming\npm\node_modules\npm\lib\cli.js:65:5)
44 verbose cwd D:\Projects\DMS\d\dhiwise-nodejs
45 verbose Windows_NT 10.0.19044
46 verbose argv "C:\\node\\node.exe" "C:\\Users\\[redacted]\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
47 verbose node v16.13.1
48 verbose npm  v8.1.4
49 error code ERESOLVE
50 error ERESOLVE unable to resolve dependency tree
51 error
52 error While resolving: [1mnodejs-code-generator[22m@[1m0.0.0[22m
52 error Found: [1mlerna[22m@[1m4.0.0[22m[2m[22m
52 error [2mnode_modules/lerna[22m
52 error   [33mdev[39m [1mlerna[22m@"[1m^4.0.0[22m" from the root project
52 error
52 error Could not resolve dependency:
52 error [35mpeer[39m [1mlerna[22m@"[1m^3.0.0[22m" from [1mcz-lerna-changelog[22m@[1m2.0.3[22m[2m[22m
52 error [2mnode_modules/cz-lerna-changelog[22m
52 error   [33mdev[39m [1mcz-lerna-changelog[22m@"[1m^2.0.3[22m" from the root project
52 error
52 error Fix the upstream dependency conflict, or retry
52 error this command with --force, or --legacy-peer-deps
52 error to accept an incorrect (and potentially broken) dependency resolution.
52 error
52 error See C:\Users\[redacted]\AppData\Local\npm-cache\eresolve-report.txt for a full report.
53 verbose exit 1

```

forcing with `--legacy-peer-deps` appears to work

**Comment by saloni137** [comment]
This issue is resolved here https://github.com/DhiWise/dhiwise-nodejs/issues/10. check it out.
The workaround for this is use ```npm i --force``` instead of ```npm i ```

**Comment by 0x41mmarVM** [comment]
@saloni137 umm.. not to quibble, but "workaround available" is really not the same as "resolved", but I see how this is unsolvable at the moment, since we need the guys at atlassian to [merge this](https://github.com/atlassian/cz-lerna-changelog/pull/26). 

Thanks for your help.
