### ISSUE TITLE
[BUG] Infinite Loading in Browser

### ISSUE THREAD

**Issue by VivienRg** [DhiWise/dhiwise-nodejs#40]
### Current Behavior:
In browser the logo is continiously loading, without making any progress.
I also had to install using npm i --force

### Expected Behavior:
Taken to on boarding

### Steps To Reproduce:
npm i --force
npm run

In browser console: 
`[HMR] Waiting for update signal from WDS...
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: LoadableComponent

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at LoadableComponent (http://localhost:3000/static/js/vendors~main.chunk.js:36350:7)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:39892:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:40061:29)
    at App
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:39564:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:39078:35)
    at ToastProvider (http://localhost:3000/static/js/vendors~main.chunk.js:41554:5)
    at PersistGate (http://localhost:3000/static/js/vendors~main.chunk.js:54213:5)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:36562:20)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/vendors~main.chunk.js:50220:3)
    at RecoilRoot (http://localhost:3000/static/js/vendors~main.chunk.js:50359:5)
    at MainApp
    at App
console.<computed> @ index.js:1
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
(anonymous) @ react-dom.development.js:11587
push.../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushLegacyContextWarning @ react-dom.development.js:11571
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23819
commitRootImpl @ react-dom.development.js:23005
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push.../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
dispatch @ redux.js:288
(anonymous) @ serializableStateInvariantMiddleware.ts:210
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:266
(anonymous) @ actionCreatorInvariantMiddleware.ts:32
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ App.js:13
./src/App.js @ App.js:37
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ buildProcessConstant.js:23
./src/index.js @ index.js:21
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ reportWebVitals.js:16
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
react-dom.development.js:67 Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: LoadableComponent
printWarning @ react-dom.development.js:67
warn @ react-dom.development.js:34
push.../../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11524
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23822
commitRootImpl @ react-dom.development.js:23005
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
enqueueSetState @ react-dom.development.js:12467
push.../../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:365
(anonymous) @ react.js:61
dispatch @ redux.js:297
rehydrate @ persistStore.js:79
_rehydrate @ persistReducer.js:61
(anonymous) @ persistReducer.js:90
Promise.then (async)
(anonymous) @ persistReducer.js:89
Promise.then (async)
(anonymous) @ persistReducer.js:84
dispatch @ redux.js:288
(anonymous) @ serializableStateInvariantMiddleware.ts:210
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:266
(anonymous) @ actionCreatorInvariantMiddleware.ts:32
persist @ persistStore.js:114
persistStore @ persistStore.js:123
(anonymous) @ App.js:13
./src/App.js @ App.js:37
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ buildProcessConstant.js:23
./src/index.js @ index.js:21
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ reportWebVitals.js:16
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
2index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'SetArray' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'TraceMap' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.mjs
Can't import the named export 'decode' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'decodedMappings' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.mjs
Can't import the named export 'encode' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'encode' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
4index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.mjs
Can't import the named export 'put' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
index.js:1 /Users/vivienroggero/Documents/source/dhiwise-nodejs/node_modules/@monaco-editor/react/dist/index.mjs 124:62
Module parse failed: Unexpected token (124:62)
File was processed with these loaders:
 * ../../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   k(() => {
|     let i = Se.init();
>     return i.then(f => (c.current = f) && s(!1)).catch(f => f?.type !== "cancelation" && console.error("Monaco initialization: error:", f)), () => u.current ? I() : i.cancel();
|   }), l(() => {
|     if (u.current && c.current) {
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213
VM260:2 Uncaught ReferenceError: process is not defined
    at 4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at 8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at 8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at e.onload (index.js:1:1)`

### Environment:
- OS: Mac os Ventura 13.0
- Node: v16.15.1
- npm: 9.8.1

**Comment by RedSpeeds** [comment]
Got the same issue anyone know how to fix this?

**Comment by Blabbone** [comment]
Same error. Repo without maintenance

For people going crazy trying to find the right version of node:
nodejs - 14.21.3
npm - 6.14.18

**Comment by muditgupta-codez** [comment]
Did anyone found fix to this?

**Comment by meetdhanani17** [comment]
> Did anyone found fix to this?

you should try this https://github.com/meetdhanani17/dhiwise-nodejs/tree/fix/server_start_errors, in that i have try to solve issue and its working for me, if any issue found in this repository please don't create issue in dhiwise-nodejs official repository because i have removed some things that occurs error, after successful testing i will raise pr to dhiwise-nodejs official repository

**Comment by akshay-inovar** [comment]
> > Did anyone found fix to this?
> 
> you should try this https://github.com/meetdhanani17/dhiwise-nodejs/tree/fix/server_start_errors, in that i have try to solve issue and its working for me, if any issue found in this repository please don't create issue in dhiwise-nodejs official repository because i have removed some things that occurs error, after successful testing i will raise pr to dhiwise-nodejs official repository

any specific node version?

**Comment by meetdhanani17** [comment]
Use 18 or above

**Comment by sky4hostwael** [comment]
> Use 18 or above


I have more than one request and question in your repo

1- You said that the dependencies must be installed in the client first, then the server, then the root
But when I install the root dependencies, it deletes the client and server dependencies and reinstalls them again
Please write the complete installation instructions in order
2- After running the project and now everything is working, I noticed two problems
The first is that there is no dashboard showing me the projects that I have done, and in this case, how can I go back or choose another project to complete work on it
The second problem, which is the most important
I cannot do a build after half an hour of running the project, the build button is disabled, and if it is not disabled, an error message appears in the server
Thank you
@meetdhanani17
